[package]
name = "comprexor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.25"
humansize = "2.1.3"
owo-colors = "3.5.0"
rand = "0.8.5"
tar = "0.4.38"
walkdir = "2.3.3"
